module.exports = {
  LOG: "log",
  MESSAGE: "message",
  PRIVATE_MESSAGE: "private_message",
  ERROR: "error",
  INITIAL: "initial",
  CHECK_TOKEN_VALIDITY: "check_token",
  JOIN: "join",
  UPDATE_TOKEN: "update_token",
  CLOSE: "close",
  GET_TOKEN: "get_token",
  INVITE_TO_CHAT: "invite_to_private_chat",
  REJECT_INVITATION: "reject_chat_invitation",
  ACCEPT_INVITATION: "accept_chat_invitation",
};
